name : Project Executor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  kaggle_user: ${{secrets.KAGGLE_CRED}}

jobs:
  project-executor:
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
#        with:
#          path: project

      # Install python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

        # Install Libraries
      - name: Setting Up Environment Requirements
        id: requirements-set-up
        uses: py-actions/py-dependency-install@v4
        with:
          path: "requirements.txt"

      - name: Kaggle credentials
        env:
          KAGGLE_USER: ${{ secrets.KAGGLE_USER }}
          KAGGLE_TOKEN: ${{ secrets.KAGGLE_TOKEN }}
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"${{ secrets.KAGGLE_USER }}\",\"key\":\"${{ secrets.KAGGLE_TOEKN }}\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      #run test.sh
      - name: Running automated test case
        id: test-run
        shell: bash
        run: chmod +x ./project/tests.sh

